version: "2"
linters:
  enable:
    - asasalint
    - asciicheck
    - bodyclose
    - dupword
    - durationcheck
    - errname
    - errorlint
    - exhaustive
    - gocheckcompilerdirectives
    - gocritic
    - godot
    - goprintffuncname
    - gosec
    - grouper
    - makezero
    - nilerr
    - nilnil
    - nolintlint
    - nosprintfhostport
    - prealloc
    - predeclared
    - reassign
    - staticcheck
    - testableexamples
    - thelper
    - tparallel
    - unconvert
    - unparam
    - usestdlibvars
    - wastedassign
    - whitespace
    - zerologlint
  exclusions:
    generated: lax
    presets:
      - comments
      - common-false-positives
      - legacy
      - std-error-handling
    rules:
      - linters:
          - goconst
        path: (.+)_test\.go
      - linters:
          - govet
        path: (.+)_test\.go
        text: 'fieldalignment: .*'
    paths:
      - third_party$
      - builtin$
      - examples$
issues:
  max-issues-per-linter: 0
  max-same-issues: 0
  fix: false
formatters:
  enable:
    - gofmt
    - goimports
  exclusions:
    generated: lax
    paths:
      - third_party$
      - builtin$
      - examples$
