{
 "title": "Saltstack",
 "time": { "from": "now-1h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "function",
    "query": {
     "query": "query_result(salt_scheduled_job_return_total or salt_new_job_total or salt_function_responses_total)"
    }
   },
   {
    "name": "state",
    "query": {
     "query": "query_result(salt_scheduled_job_return_total{function=~\"$function\"} or salt_new_job_total{function=~\"$function\"} or salt_function_responses_total{function=~\"$function\"})"
    }
   }
  ]
 },
 "panels": [
  { "title": "Jobs", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "New job",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 1 },
   "targets": [
    {
     "expr": "sum by (function, state) (increase(salt_new_job_total{function=~\"$function\", state=~\"$state\"}[$__rate_interval]))",
     "legendFormat": "\"{{function}} {{state}}\""
    }
   ]
  },
  {
   "title": "Missing responses",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 1 },
   "targets": [
    {
     "expr": "sum by (instance, function, state) (increase(salt_expected_responses_total{function=~\"$function\", state=~\"$state\"}[$__rate_interval])) - sum by (instance, function, state) (increase(salt_function_responses_total{function=~\"$function\", state=~\"$state\"}[$__rate_interval]))",
     "legendFormat": "\"{{function}} {{state}}\""
    }
   ]
  },
  {
   "title": "Response success",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 10 },
   "targets": [
    {
     "expr": "sum by (instance, function, state) (increase(salt_function_responses_total{function=~\"$function\", state=~\"$state\",success=\"true\"}[$__rate_interval]))",
     "legendFormat": "\"{{function}} {{state}}\""
    }
   ]
  },
  {
   "title": "Response success",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 10 },
   "targets": [
    {
     "expr": "- sum by (instance, function, state) (increase(salt_function_responses_total{function=~\"$function\", state=~\"$state\", success=\"false\"}[$__rate_interval]))",
     "legendFormat": "\"{{function}} {{state}}\""
    }
   ]
  },
  { "title": "Scheduled jobs", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 19 } },
  {
   "title": "Scheduled job responses",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 20 },
   "targets": [
    {
     "expr": "sum by (function, state) (increase(salt_scheduled_job_return_total{function=~\"$function\", state=~\"$state\", success=\"true\"}[$__rate_interval]))",
     "legendFormat": "\"{{function}} {{state}}\""
    },
    {
     "expr": "- sum by (function, state) (increase(salt_scheduled_job_return_total{function=~\"$function\", state=~\"$state\", success=\"false\"}[$__rate_interval]))",
     "legendFormat": "\"{{function}} {{state}}\""
    }
   ]
  }
 ]
}